; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool on Thu Oct 06 2016 12:46:23 GMT-0400 (Eastern Daylight Time)

; Clear any bed transform
M561

; Probe the bed at 5 points
G30 P0 X15 Y15 H0 Z-99999
G30 P1 X15 Y285 H0 Z-99999
G30 P2 X385 Y285 H0 Z-99999
G30 P3 X385 Y15 H0 Z-99999
G30 P4 X200 Y150 H0 Z-99999 S

