; homey.g
; called to home the Y axis
;
; generated by RepRapFirmware Configuration Tool on Thu Oct 06 2016 12:46:23 GMT-0400 (Eastern Daylight Time)

; Lift Z relative to current position
G91
G1 Z5 S2 F9000

; Move quickly to Y axis endstop and stop there (first pass)
G1 Y-305 F3000 S1

; Go back a few mm
G1 Y5 F9000

; Move slowly to X axis endstop once more (second pass)
G1 Y-305 F360 S1

; Lower Z again
G1 Z-5 S2 F9000
G90
