; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool on Thu Oct 06 2016 12:46:23 GMT-0400 (Eastern Daylight Time)

; Lift Z relatively to current position
G91
G1 Z5 S2 F9000
G90

; Go to center and home the Z axis
G1 X200 Y150 F9000
G30
; Uncomment the following lines to lift Z after probing
;G1 Z5 S2 F150
;G90