; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Thu Oct 06 2016 12:46:23 GMT-0400 (Eastern Daylight Time)

; Wait for set temperatures to be reached
M116 P0
